// ------------- Register ------------- \\
POST http://localhost:3000/api/v1/register
Content-Type: application/json

{
    "name": "Pesho",
    "password": "123",
    "age": 20,
    "email": "kristian.petrov1998@gmail.com"
}

###
// ------------- Login ------------- \\
POST http://localhost:3000/api/v1/login
Content-Type: application/json

{
    "password": "123",
    "email": "kristian.petrov1998@gmail.com"

}

// ------------- Get Access Token ------------- \\
###
POST http://localhost:3000/api/v1/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWMxNTdhOTM4OWZkOWU3OTc1MmRiNSIsImlhdCI6MTY3OTU2MjUwNSwiZXhwIjoxNjgwNDI2NTA1fQ.h8vhUe4A24Ob5_HLRFRv5l2gJYwISl6XsZ_jIKvf3gQ"
}

###
// ------------- Logout/delete refresh token ------------- \\
PATCH http://localhost:3000/api/v1/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MTgzZDg0ZDYzNTc5YTI2MjY2MzdkYyIsImlhdCI6MTY3OTMyNzUzOSwiZXhwIjoxNjgwMTkxNTM5fQ.P-X3BvqFBEBUD1p2-ON6UYqkPJF0JOTL4Pe627hcPYo"
}

###
// ------------- Edit user ------------- \\
PATCH http://localhost:3000/api/v1/edit-user/641c16bff29e0b12a7ae8277
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWMxNTdhOTM4OWZkOWU3OTc1MmRiNSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTY3OTU3NzY5MywiZXhwIjoxNjc5NTc4ODkzfQ.9htwYqyuV7JcDiniaqZL6OnOIPJxXTPTl8Fr9T-SPl0",
    "name": "Krisko"
}

### 
// ------------- Get user with posts ------------- \\
GET http://localhost:3000/api/v1/users/641c16bff29e0b12a7ae8277
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWMxNmJmZjI5ZTBiMTJhN2FlODI3NyIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjgwMzU5NDg2LCJleHAiOjE2ODAzNjA2ODZ9.-Fha2_jdzrufQf0bQE7WYylME2opD7lT_3X97rBLvWs"
}

###
// ------------- Follow ------------- \\
GET http://localhost:3000/api/v1/follow-user/641c16bff29e0b12a7ae8277
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWMxNmJmZjI5ZTBiMTJhN2FlODI3NyIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjgwMzU5NDg2LCJleHAiOjE2ODAzNjA2ODZ9.-Fha2_jdzrufQf0bQE7WYylME2opD7lT_3X97rBLvWs"
}

###
// ------------- Unfollow ------------- \\
GET http://localhost:3000/api/v1/unfollow-user/641c16bff29e0b12a7ae8277
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MWMxNmJmZjI5ZTBiMTJhN2FlODI3NyIsInJvbGUiOiJVc2VyIiwiaWF0IjoxNjgwMzU5NDg2LCJleHAiOjE2ODAzNjA2ODZ9.-Fha2_jdzrufQf0bQE7WYylME2opD7lT_3X97rBLvWs"
}
